package view.graphic;

public enum Resource {
    LABEL("skin/label/label.json"),
    SCROLL_PANE("skin/scrollPane/scrollPane.json"),
    TEXT_FIELD("skin/textField/textField.json"),
    CHANGE_EMAIL_ON("button/changeEmail/on.png"),
    CHANGE_EMAIL_OFF("button/changeEmail/off.png"),
    CHANGE_EMAIL_CLICKED("button/changeEmail/clicked.png"),
    CHANGE_NICKNAME_ON("button/changeNickname/on.png"),
    CHANGE_NICKNAME_OFF("button/changeNickname/off.png"),
    CHANGE_NICKNAME_CLICKED("button/changeNickname/clicked.png"),
    CHANGE_PASSWORD_ON("button/changePassword/on.png"),
    CHANGE_PASSWORD_OFF("button/changePassword/off.png"),
    CHANGE_PASSWORD_CLICKED("button/changePassword/clicked.png"),
    CHANGE_TURN_ON("button/changeTurn/on.png"),
    CHANGE_TURN_OFF("button/changeTurn/off.png"),
    CHANGE_TURN_CLICKED("button/changeTurn/clicked.png"),
    CHANGE_USERNAME_ON("button/changeUsername/on.png"),
    CHANGE_USERNAME_OFF("button/changeUsername/off.png"),
    CHANGE_USERNAME_CLICKED("button/changeUsername/clicked.png"),
    EXIT_GAME_ON("button/exitGame/on.png"),
    EXIT_GAME_OFF("button/exitGame/off.png"),
    EXIT_GAME_CLICKED("button/exitGame/clicked.png"),
    EXIT_MENU_ON("button/exitMenu/on.png"),
    EXIT_MENU_OFF("button/exitMenu/off.png"),
    EXIT_MENU_CLICKED("button/exitMenu/clicked.png"),
    FORGET_PASSWORD_ON("button/forgetPassword/on.png"),
    FORGET_PASSWORD_OFF("button/forgetPassword/off.png"),
    FORGET_PASSWORD_CLICKED("button/forgetPassword/clicked.png"),
    GAME_MENU_ON("button/gameMenu/on.png"),
    GAME_MENU_OFF("button/gameMenu/off.png"),
    GAME_MENU_CLICKED("button/gameMenu/clicked.png"),
    LOGIN_MENU_ON("button/loginMenu/on.png"),
    LOGIN_MENU_OFF("button/loginMenu/off.png"),
    LOGIN_MENU_CLICKED("button/loginMenu/clicked.png"),
    LOGIN_ON("button/login/on.png"),
    LOGIN_OFF("button/login/off.png"),
    LOGIN_CLICKED("button/login/clicked.png"),
    MAIN_MENU_ON("button/mainMenu/on.png"),
    MAIN_MENU_OFF("button/mainMenu/off.png"),
    MAIN_MENU_CLICKED("button/mainMenu/clicked.png"),
    NORMAL_HISTORY_ON("button/normalHistory/on.png"),
    NORMAL_HISTORY_OFF("button/normalHistory/off.png"),
    NORMAL_HISTORY_CLICKED("button/normalHistory/clicked.png"),
    PROFILE_MENU_ON("button/profileMenu/on.png"),
    PROFILE_MENU_OFF("button/profileMenu/off.png"),
    PROFILE_MENU_CLICKED("button/profileMenu/clicked.png"),
    REGISTER_MENU_ON("button/registerMenu/on.png"),
    REGISTER_MENU_OFF("button/registerMenu/off.png"),
    REGISTER_MENU_CLICKED("button/registerMenu/clicked.png"),
    REGISTER_ON("button/register/on.png"),
    REGISTER_OFF("button/register/off.png"),
    REGISTER_CLICKED("button/register/clicked.png"),
    SAVE_DECK_ON("button/saveDeck/on.png"),
    SAVE_DECK_OFF("button/saveDeck/off.png"),
    SAVE_DECK_CLICKED("button/saveDeck/clicked.png"),
    SAVE_EXTERNAL_DECK_ON("button/saveExternalDeck/on.png"),
    SAVE_EXTERNAL_DECK_OFF("button/saveExternalDeck/off.png"),
    SAVE_EXTERNAL_DECK_CLICKED("button/saveExternalDeck/clicked.png"),
    SET_NEW_PASSWORD_ON("button/setNewPassword/on.png"),
    SET_NEW_PASSWORD_OFF("button/setNewPassword/off.png"),
    SET_NEW_PASSWORD_CLICKED("button/setNewPassword/clicked.png"),
    SPECIFIED_HISTORY_ON("button/specifiedHistory/on.png"),
    SPECIFIED_HISTORY_OFF("button/specifiedHistory/off.png"),
    SPECIFIED_HISTORY_CLICKED("button/specifiedHistory/clicked.png"),
    START_MENU_ON("button/startMenu/on.png"),
    START_MENU_OFF("button/startMenu/off.png"),
    START_MENU_CLICKED("button/startMenu/clicked.png"),
    SAVE_ON("button/save/on.png"),
    SAVE_OFF("button/save/off.png"),
    SAVE_CLICKED("button/save/clicked.png"),
    HISTORY_ON("button/history/on.png"),
    HISTORY_OFF("button/history/off.png"),
    HISTORY_CLICKED("button/history/clicked.png"),
    LOGOUT_ON("button/logout/on.png"),
    LOGOUT_OFF("button/logout/off.png"),
    LOGOUT_CLICKED("button/logout/clicked.png"),
    LOGIN_BACKGROUND("background/login.jpg"),
    REGISTER_BACKGROUND("background/register.jpg"),
    MAIN_BACKGROUND("background/main.jpg"),
    PROFILE_BACKGROUND("background/profile.jpg"),;
    private String address;

    Resource(String address) {
        this.address = address;
    }

    public String address() {
        return address;
    }
}
